package mapping;



/**
 * AdottantiviewId generated by hbm2java
 */

public class AdottantiviewId  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Integer idanagrafe;
     private String cognome;
     private String nome;
     private Integer idbambino;
     private String nomebambino;
     private Integer anno;
     private Integer p1;
     private Integer p2;
     private Integer p3;
     private Integer costo;


     // Constructors

     public Integer getCosto() {
 		return costo;
 	}





 	public void setCosto(Integer costo) {
 		this.costo = costo;
 	}


    // Constructors

    /** default constructor */
    public AdottantiviewId() {
    }
    

    

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getIdanagrafe() {
        return this.idanagrafe;
    }
    
    public void setIdanagrafe(Integer idanagrafe) {
        this.idanagrafe = idanagrafe;
    }

    public String getCognome() {
        return this.cognome;
    }
    
    public void setCognome(String cognome) {
        this.cognome = cognome;
    }

    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    public Integer getIdbambino() {
        return this.idbambino;
    }
    
    public void setIdbambino(Integer idbambino) {
        this.idbambino = idbambino;
    }

    public String getNomebambino() {
        return this.nomebambino;
    }
    
    public void setNomebambino(String nomebambino) {
        this.nomebambino = nomebambino;
    }

    public Integer getAnno() {
        return this.anno;
    }
    
    public void setAnno(Integer anno) {
        this.anno = anno;
    }

    public Integer getP1() {
        return this.p1;
    }
    
    public void setP1(Integer p1) {
        this.p1 = p1;
    }

    public Integer getP2() {
        return this.p2;
    }
    
    public void setP2(Integer p2) {
        this.p2 = p2;
    }

    public Integer getP3() {
        return this.p3;
    }
    
    public void setP3(Integer p3) {
        this.p3 = p3;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AdottantiviewId) ) return false;
		 AdottantiviewId castOther = ( AdottantiviewId ) other; 
         
		 return ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
 && ( (this.getIdanagrafe()==castOther.getIdanagrafe()) || ( this.getIdanagrafe()!=null && castOther.getIdanagrafe()!=null && this.getIdanagrafe().equals(castOther.getIdanagrafe()) ) )
 && ( (this.getCognome()==castOther.getCognome()) || ( this.getCognome()!=null && castOther.getCognome()!=null && this.getCognome().equals(castOther.getCognome()) ) )
 && ( (this.getNome()==castOther.getNome()) || ( this.getNome()!=null && castOther.getNome()!=null && this.getNome().equals(castOther.getNome()) ) )
 && ( (this.getIdbambino()==castOther.getIdbambino()) || ( this.getIdbambino()!=null && castOther.getIdbambino()!=null && this.getIdbambino().equals(castOther.getIdbambino()) ) )
 && ( (this.getNomebambino()==castOther.getNomebambino()) || ( this.getNomebambino()!=null && castOther.getNomebambino()!=null && this.getNomebambino().equals(castOther.getNomebambino()) ) )
 && ( (this.getAnno()==castOther.getAnno()) || ( this.getAnno()!=null && castOther.getAnno()!=null && this.getAnno().equals(castOther.getAnno()) ) )
 && ( (this.getP1()==castOther.getP1()) || ( this.getP1()!=null && castOther.getP1()!=null && this.getP1().equals(castOther.getP1()) ) )
 && ( (this.getP2()==castOther.getP2()) || ( this.getP2()!=null && castOther.getP2()!=null && this.getP2().equals(castOther.getP2()) ) )
 && ( (this.getP3()==castOther.getP3()) || ( this.getP3()!=null && castOther.getP3()!=null && this.getP3().equals(castOther.getP3()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         result = 37 * result + ( getIdanagrafe() == null ? 0 : this.getIdanagrafe().hashCode() );
         result = 37 * result + ( getCognome() == null ? 0 : this.getCognome().hashCode() );
         result = 37 * result + ( getNome() == null ? 0 : this.getNome().hashCode() );
         result = 37 * result + ( getIdbambino() == null ? 0 : this.getIdbambino().hashCode() );
         result = 37 * result + ( getNomebambino() == null ? 0 : this.getNomebambino().hashCode() );
         result = 37 * result + ( getAnno() == null ? 0 : this.getAnno().hashCode() );
         result = 37 * result + ( getP1() == null ? 0 : this.getP1().hashCode() );
         result = 37 * result + ( getP2() == null ? 0 : this.getP2().hashCode() );
         result = 37 * result + ( getP3() == null ? 0 : this.getP3().hashCode() );
         return result;
   }   





}