package mapping;



/**
 * Adottantiview generated by hbm2java
 */

public class Adottantiview  implements java.io.Serializable {


    // Fields    

     private AdottantiviewId id;


    // Constructors

    /** default constructor */
    public Adottantiview() {
    }
    
    /** constructor with id */
    public Adottantiview(AdottantiviewId id) {
        this.id = id;
    }

    

   
    // Property accessors

    public AdottantiviewId getId() {
        return this.id;
    }
    
    public void setId(AdottantiviewId id) {
        this.id = id;
    }
   








}