package mapping;



/**
 * BambiniliberiId generated by hbm2java
 */

public class BambiniliberiId  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String nome;
     private String sesso;
     private String citta;
     private String nazione;
     private String scuola;
     private Integer anno;
     private Integer costo;


     // Constructors

     public Integer getCosto() {
 		return costo;
 	}





 	public void setCosto(Integer costo) {
 		this.costo = costo;
 	}


    // Constructors

    /** default constructor */
    public BambiniliberiId() {
    }
    

    

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getSesso() {
        return this.sesso;
    }
    
    public void setSesso(String sesso) {
        this.sesso = sesso;
    }

    public String getCitta() {
        return this.citta;
    }
    
    public void setCitta(String citta) {
        this.citta = citta;
    }

    public String getNazione() {
        return this.nazione;
    }
    
    public void setNazione(String nazione) {
        this.nazione = nazione;
    }

    public String getScuola() {
        return this.scuola;
    }
    
    public void setScuola(String scuola) {
        this.scuola = scuola;
    }

    public Integer getAnno() {
        return this.anno;
    }
    
    public void setAnno(Integer anno) {
        this.anno = anno;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BambiniliberiId) ) return false;
		 BambiniliberiId castOther = ( BambiniliberiId ) other; 
         
		 return ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
 && ( (this.getNome()==castOther.getNome()) || ( this.getNome()!=null && castOther.getNome()!=null && this.getNome().equals(castOther.getNome()) ) )
 && ( (this.getSesso()==castOther.getSesso()) || ( this.getSesso()!=null && castOther.getSesso()!=null && this.getSesso().equals(castOther.getSesso()) ) )
 && ( (this.getCitta()==castOther.getCitta()) || ( this.getCitta()!=null && castOther.getCitta()!=null && this.getCitta().equals(castOther.getCitta()) ) )
 && ( (this.getNazione()==castOther.getNazione()) || ( this.getNazione()!=null && castOther.getNazione()!=null && this.getNazione().equals(castOther.getNazione()) ) )
 && ( (this.getScuola()==castOther.getScuola()) || ( this.getScuola()!=null && castOther.getScuola()!=null && this.getScuola().equals(castOther.getScuola()) ) )
 && ( (this.getAnno()==castOther.getAnno()) || ( this.getAnno()!=null && castOther.getAnno()!=null && this.getAnno().equals(castOther.getAnno()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         result = 37 * result + ( getNome() == null ? 0 : this.getNome().hashCode() );
         result = 37 * result + ( getSesso() == null ? 0 : this.getSesso().hashCode() );
         result = 37 * result + ( getCitta() == null ? 0 : this.getCitta().hashCode() );
         result = 37 * result + ( getNazione() == null ? 0 : this.getNazione().hashCode() );
         result = 37 * result + ( getScuola() == null ? 0 : this.getScuola().hashCode() );
         result = 37 * result + ( getAnno() == null ? 0 : this.getAnno().hashCode() );
         return result;
   }   





}