package mapping;



/**
 * Bambiniliberi generated by hbm2java
 */

public class Bambiniliberi  implements java.io.Serializable {


    // Fields    

     private BambiniliberiId id;


    // Constructors

    /** default constructor */
    public Bambiniliberi() {
    }
    
    /** constructor with id */
    public Bambiniliberi(BambiniliberiId id) {
        this.id = id;
    }

    

   
    // Property accessors

    public BambiniliberiId getId() {
        return this.id;
    }
    
    public void setId(BambiniliberiId id) {
        this.id = id;
    }
   








}