package mapping;

import java.util.Date;
import java.util.Set;


/**
 * Bambino generated by hbm2java
 */

public class Bambino  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String nome;
     private String sesso;
     private String indirizzo;
     private String citta;
     private String nazione;
     private Date datanascita;
     private String scuola;
     private String descrizione;
     private Set bambinoannos;
     private Set adottantis;


    // Constructors

    /** default constructor */
    public Bambino() {
    }
    
    /** constructor with id */
    public Bambino(Integer id) {
        this.id = id;
    }

    

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getSesso() {
        return this.sesso;
    }
    
    public void setSesso(String sesso) {
        this.sesso = sesso;
    }

    public String getIndirizzo() {
        return this.indirizzo;
    }
    
    public void setIndirizzo(String indirizzo) {
        this.indirizzo = indirizzo;
    }

    public String getCitta() {
        return this.citta;
    }
    
    public void setCitta(String citta) {
        this.citta = citta;
    }

    public String getNazione() {
        return this.nazione;
    }
    
    public void setNazione(String nazione) {
        this.nazione = nazione;
    }

    public Date getDatanascita() {
        return this.datanascita;
    }
    
    public void setDatanascita(Date datanascita) {
        this.datanascita = datanascita;
    }

    public String getScuola() {
        return this.scuola;
    }
    
    public void setScuola(String scuola) {
        this.scuola = scuola;
    }

    public String getDescrizione() {
        return this.descrizione;
    }
    
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    public Set getBambinoannos() {
        return this.bambinoannos;
    }
    
    public void setBambinoannos(Set bambinoannos) {
        this.bambinoannos = bambinoannos;
    }

    public Set getAdottantis() {
        return this.adottantis;
    }
    
    public void setAdottantis(Set adottantis) {
        this.adottantis = adottantis;
    }
   








}