package mapping;

import java.util.Set;


/**
 * Categorienews generated by hbm2java
 */

public class Categorienews  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String nome;
     private String descrizione;
     private Set newses;


    // Constructors

    /** default constructor */
    public Categorienews() {
    }
    
    /** constructor with id */
    public Categorienews(Integer id) {
        this.id = id;
    }

    

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getDescrizione() {
        return this.descrizione;
    }
    
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    public Set getNewses() {
        return this.newses;
    }
    
    public void setNewses(Set newses) {
        this.newses = newses;
    }
   








}