package mapping;



/**
 * Contogruppo generated by hbm2java
 */

public class Contogruppo  implements java.io.Serializable {


    // Fields    

     private ContogruppoId id;


    // Constructors

    /** default constructor */
    public Contogruppo() {
    }
    
    /** constructor with id */
    public Contogruppo(ContogruppoId id) {
        this.id = id;
    }

    

   
    // Property accessors

    public ContogruppoId getId() {
        return this.id;
    }
    
    public void setId(ContogruppoId id) {
        this.id = id;
    }
   








}