package mapping;

import java.util.Set;


/**
 * Conto generated by hbm2java
 */

public class Conto  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Gruppo gruppo;
     private String nome;
     private boolean mostra;
     private Set movimentisForDare;
     private Set scritturasForAvere;
     private Set movimentisForAvere;
     private Set scritturasForDare;


    // Constructors

    /** default constructor */
    public Conto() {
    }
    
    /** constructor with id */
    public Conto(Integer id) {
        this.id = id;
    }

    

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Gruppo getGruppo() {
        return this.gruppo;
    }
    
    public void setGruppo(Gruppo gruppo) {
        this.gruppo = gruppo;
    }

    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    public Set getMovimentisForDare() {
        return this.movimentisForDare;
    }
    
    public void setMovimentisForDare(Set movimentisForDare) {
        this.movimentisForDare = movimentisForDare;
    }

    public Set getScritturasForAvere() {
        return this.scritturasForAvere;
    }
    
    public void setScritturasForAvere(Set scritturasForAvere) {
        this.scritturasForAvere = scritturasForAvere;
    }

    public Set getMovimentisForAvere() {
        return this.movimentisForAvere;
    }
    
    public void setMovimentisForAvere(Set movimentisForAvere) {
        this.movimentisForAvere = movimentisForAvere;
    }

    public Set getScritturasForDare() {
        return this.scritturasForDare;
    }
    
    public void setScritturasForDare(Set scritturasForDare) {
        this.scritturasForDare = scritturasForDare;
    }

	public boolean isMostra() {
		return mostra;
	}

	public void setMostra(boolean mostra) {
		this.mostra = mostra;
	}
   








}