package mapping;

import java.util.Date;


/**
 * Eventi generated by hbm2java
 */

public class Eventi  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private News news;
     private String titolo;
     private String luogo;
     private Date data;
     private String ora;


    // Constructors

    /** default constructor */
    public Eventi() {
    }
    
    /** constructor with id */
    public Eventi(Integer id) {
        this.id = id;
    }

    

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public News getNews() {
        return this.news;
    }
    
    public void setNews(News news) {
        this.news = news;
    }

    public String getTitolo() {
        return this.titolo;
    }
    
    public void setTitolo(String titolo) {
        this.titolo = titolo;
    }

    public String getLuogo() {
        return this.luogo;
    }
    
    public void setLuogo(String luogo) {
        this.luogo = luogo;
    }

    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }

    public String getOra() {
        return this.ora;
    }
    
    public void setOra(String ora) {
        this.ora = ora;
    }
   








}