package mapping;

import java.util.Date;


/**
 * High generated by hbm2java
 */

public class High  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private News news;
     private Date data;
     private String testo;
     private Integer visibile;


    // Constructors

    /** default constructor */
    public High() {
    }
    
    /** constructor with id */
    public High(Integer id) {
        this.id = id;
    }

    

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public News getNews() {
        return this.news;
    }
    
    public void setNews(News news) {
        this.news = news;
    }

    public Date getData() {
        return this.data;
    }
    
    public void setData(Date data) {
        this.data = data;
    }

    public String getTesto() {
        return this.testo;
    }
    
    public void setTesto(String testo) {
        this.testo = testo;
    }

    public Integer getVisibile() {
        return this.visibile;
    }
    
    public void setVisibile(Integer visibile) {
        this.visibile = visibile;
    }
   








}