package mapping;



/**
 * Movimenti generated by hbm2java
 */

public class Movimenti  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Conto dare;
     private Conto avere;
     private String descrizione;
     private String nome;


    // Constructors

    /** default constructor */
    public Movimenti() {
    }
    
    /** constructor with id */
    public Movimenti(Integer id) {
        this.id = id;
    }

    

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Conto getAvere() {
		return avere;
	}

	public void setAvere(Conto avere) {
		this.avere = avere;
	}

	public Conto getDare() {
		return dare;
	}

	public void setDare(Conto dare) {
		this.dare = dare;
	}

	public String getDescrizione() {
        return this.descrizione;
    }
    
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }
   








}