package mapping;



/**
 * Newsimg generated by hbm2java
 */

public class Newsimg  implements java.io.Serializable {


    // Fields    

     private NewsimgId id;
     private Immagini immagini;
     private News news;


    // Constructors

    /** default constructor */
    public Newsimg() {
    }
    
    /** constructor with id */
    public Newsimg(NewsimgId id) {
        this.id = id;
    }

    

   
    // Property accessors

    public NewsimgId getId() {
        return this.id;
    }
    
    public void setId(NewsimgId id) {
        this.id = id;
    }

    public Immagini getImmagini() {
        return this.immagini;
    }
    
    public void setImmagini(Immagini immagini) {
        this.immagini = immagini;
    }

    public News getNews() {
        return this.news;
    }
    
    public void setNews(News news) {
        this.news = news;
    }
   








}