package mapping;



/**
 * Nonsoci generated by hbm2java
 */

public class Nonsoci  implements java.io.Serializable {


    // Fields    

     private NonsociId id;


    // Constructors

    /** default constructor */
    public Nonsoci() {
    }
    
    /** constructor with id */
    public Nonsoci(NonsociId id) {
        this.id = id;
    }

    

   
    // Property accessors

    public NonsociId getId() {
        return this.id;
    }
    
    public void setId(NonsociId id) {
        this.id = id;
    }
   








}