package mapping;



/**
 * Pagamenti generated by hbm2java
 */

public class Pagamenti  implements java.io.Serializable {


    // Fields    

     private PagamentiId id;


    // Constructors

    /** default constructor */
    public Pagamenti() {
    }
    
    /** constructor with id */
    public Pagamenti(PagamentiId id) {
        this.id = id;
    }

    

   
    // Property accessors

    public PagamentiId getId() {
        return this.id;
    }
    
    public void setId(PagamentiId id) {
        this.id = id;
    }
   








}