package mapping;



/**
 * Progettiimg generated by hbm2java
 */

public class Progettiimg  implements java.io.Serializable {


    // Fields    

     private ProgettiimgId id;
     private Immagini immagini;
     private Progetti progetti;


    // Constructors

    /** default constructor */
    public Progettiimg() {
    }
    
    /** constructor with id */
    public Progettiimg(ProgettiimgId id) {
        this.id = id;
    }

    

   
    // Property accessors

    public ProgettiimgId getId() {
        return this.id;
    }
    
    public void setId(ProgettiimgId id) {
        this.id = id;
    }

    public Immagini getImmagini() {
        return this.immagini;
    }
    
    public void setImmagini(Immagini immagini) {
        this.immagini = immagini;
    }

    public Progetti getProgetti() {
        return this.progetti;
    }
    
    public void setProgetti(Progetti progetti) {
        this.progetti = progetti;
    }
   








}