package mapping;



/**
 * Soci generated by hbm2java
 */

public class Soci  implements java.io.Serializable {


    // Fields    

     private SociId id;


    // Constructors

    /** default constructor */
    public Soci() {
    }
    
    /** constructor with id */
    public Soci(SociId id) {
        this.id = id;
    }

    

   
    // Property accessors

    public SociId getId() {
        return this.id;
    }
    
    public void setId(SociId id) {
        this.id = id;
    }
   








}