package mapping;

import java.util.Set;



/**
 * Anno generated by hbm2java
 */

public class Anno  implements java.io.Serializable {


    // Fields    
     private Integer anno;
     private boolean chiuso;
     private Set scritturas;

    // Constructors

    /** default constructor */
    public Anno() {
    }
    
    /** constructor with id */
    public Anno(Integer anno) {
        this.anno = anno;
    }

    

   
    // Property accessors

    public Integer getAnno() {
        return this.anno;
    }
    
    public void setAnno(Integer anno) {
        this.anno = anno;
    }

    public boolean isChiuso() {
        return this.chiuso;
    }
    
    public void setChiuso(boolean chiuso) {
        this.chiuso = chiuso;
    }

	public Set getScritturas() {
		return this.scritturas;
	}

	public void setScritturas(Set scritturas) {
		this.scritturas = scritturas;
	}
   








}