package mapping;

/**
 * AzionistaId generated by hbm2java
 */

public class AzionistaId  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Integer anno;
     private Integer importo;
     private String note;


    // Constructors

    /** default constructor */
    public AzionistaId() {
    }
    

    

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getAnno() {
        return this.anno;
    }
    
    public void setAnno(Integer anno) {
        this.anno = anno;
    }

    public Integer getImporto() {
        return this.importo;
    }
    
    public void setImporto(Integer importo) {
        this.importo = importo;
    }

    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AzionistaId) ) return false;
		 AzionistaId castOther = ( AzionistaId ) other; 
         
		 return ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
 && ( (this.getAnno()==castOther.getAnno()) || ( this.getAnno()!=null && castOther.getAnno()!=null && this.getAnno().equals(castOther.getAnno()) ) )
 && ( (this.getImporto()==castOther.getImporto()) || ( this.getImporto()!=null && castOther.getImporto()!=null && this.getImporto().equals(castOther.getImporto()) ) )
 && ( (this.getNote()==castOther.getNote()) || ( this.getNote()!=null && castOther.getNote()!=null && this.getNote().equals(castOther.getNote()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         result = 37 * result + ( getAnno() == null ? 0 : this.getAnno().hashCode() );
         result = 37 * result + ( getImporto() == null ? 0 : this.getImporto().hashCode() );
         result = 37 * result + ( getNote() == null ? 0 : this.getNote().hashCode() );
         return result;
   }   





}