package mapping;




/**
 * Bambinoanno generated by hbm2java
 */

public class Bambinoanno  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Bambino bambino;
     private Integer anno;
     private String note;
     private Integer costo;


    // Constructors

    public Integer getCosto() {
		return costo;
	}

	public void setCosto(Integer costo) {
		this.costo = costo;
	}

	/** default constructor */
    public Bambinoanno() {
    }
    
    /** constructor with id */
    public Bambinoanno(Integer id) {
        this.id = id;
    }

    

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Bambino getBambino() {
        return this.bambino;
    }
    
    public void setBambino(Bambino bambino) {
        this.bambino = bambino;
    }

    public Integer getAnno() {
        return this.anno;
    }
    
    public void setAnno(Integer anno) {
        this.anno = anno;
    }

    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }
   








}