package mapping;



/**
 * Bambinoannoview generated by hbm2java
 */

public class Bambinoannoview  implements java.io.Serializable {


    // Fields    

     private BambinoannoviewId id;


    // Constructors

    /** default constructor */
    public Bambinoannoview() {
    }
    
    /** constructor with id */
    public Bambinoannoview(BambinoannoviewId id) {
        this.id = id;
    }

    

   
    // Property accessors

    public BambinoannoviewId getId() {
        return this.id;
    }
    
    public void setId(BambinoannoviewId id) {
        this.id = id;
    }
   








}