package mapping;



/**
 * ContogruppoId generated by hbm2java
 */

public class ContogruppoId  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String nomeconto;
     private Integer gruppo;
     private String nomegruppo;
     private Integer tipo;
     private boolean mostra;


    // Constructors

    /** default constructor */
    public ContogruppoId() {
    }
    

    

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getNomeconto() {
        return this.nomeconto;
    }
    
    public void setNomeconto(String nomeconto) {
        this.nomeconto = nomeconto;
    }

    public Integer getGruppo() {
        return this.gruppo;
    }
    
    public void setGruppo(Integer gruppo) {
        this.gruppo = gruppo;
    }

    public String getNomegruppo() {
        return this.nomegruppo;
    }
    
    public void setNomegruppo(String nomegruppo) {
        this.nomegruppo = nomegruppo;
    }

    public Integer getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Integer tipo) {
        this.tipo = tipo;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ContogruppoId) ) return false;
		 ContogruppoId castOther = ( ContogruppoId ) other; 
         
		 return ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
 && ( (this.getNomeconto()==castOther.getNomeconto()) || ( this.getNomeconto()!=null && castOther.getNomeconto()!=null && this.getNomeconto().equals(castOther.getNomeconto()) ) )
 && ( (this.getGruppo()==castOther.getGruppo()) || ( this.getGruppo()!=null && castOther.getGruppo()!=null && this.getGruppo().equals(castOther.getGruppo()) ) )
 && ( (this.getNomegruppo()==castOther.getNomegruppo()) || ( this.getNomegruppo()!=null && castOther.getNomegruppo()!=null && this.getNomegruppo().equals(castOther.getNomegruppo()) ) )
 && (this.getTipo()==castOther.getTipo());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         result = 37 * result + ( getNomeconto() == null ? 0 : this.getNomeconto().hashCode() );
         result = 37 * result + ( getGruppo() == null ? 0 : this.getGruppo().hashCode() );
         result = 37 * result + ( getNomegruppo() == null ? 0 : this.getNomegruppo().hashCode() );
         result = 37 * result + (int) this.getTipo().intValue();
         return result;
   }





public boolean isMostra() {
	return mostra;
}





public void setMostra(boolean mostra) {
	this.mostra = mostra;
}   





}