package mapping;

import java.util.Set;


/**
 * Immagini generated by hbm2java
 */

public class Immagini  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String nome;
     private String img;
     private String imggrande;
     private Integer tipo;
     private Set progettiimgs;
     private Set progettis;
     private Set newsimgs;


    // Constructors

    /** default constructor */
    public Immagini() {
    }
    
    /** constructor with id */
    public Immagini(Integer id) {
        this.id = id;
    }

    

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getImg() {
        return this.img;
    }
    
    public void setImg(String img) {
        this.img = img;
    }

    public String getImggrande() {
        return this.imggrande;
    }
    
    public void setImggrande(String imggrande) {
        this.imggrande = imggrande;
    }

    public Integer getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Integer tipo) {
        this.tipo = tipo;
    }

    public Set getProgettiimgs() {
        return this.progettiimgs;
    }
    
    public void setProgettiimgs(Set progettiimgs) {
        this.progettiimgs = progettiimgs;
    }

    public Set getProgettis() {
        return this.progettis;
    }
    
    public void setProgettis(Set progettis) {
        this.progettis = progettis;
    }

    public Set getNewsimgs() {
        return this.newsimgs;
    }
    
    public void setNewsimgs(Set newsimgs) {
        this.newsimgs = newsimgs;
    }
   








}