package mapping;



/**
 * NewsimgId generated by hbm2java
 */

public class NewsimgId  implements java.io.Serializable {


    // Fields    

     private Integer idnews;
     private Integer idimg;


    // Constructors

    /** default constructor */
    public NewsimgId() {
    }
    

    

   
    // Property accessors

    public Integer getIdnews() {
        return this.idnews;
    }
    
    public void setIdnews(Integer idnews) {
        this.idnews = idnews;
    }

    public Integer getIdimg() {
        return this.idimg;
    }
    
    public void setIdimg(Integer idimg) {
        this.idimg = idimg;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof NewsimgId) ) return false;
		 NewsimgId castOther = ( NewsimgId ) other; 
         
		 return ( (this.getIdnews()==castOther.getIdnews()) || ( this.getIdnews()!=null && castOther.getIdnews()!=null && this.getIdnews().equals(castOther.getIdnews()) ) )
 && ( (this.getIdimg()==castOther.getIdimg()) || ( this.getIdimg()!=null && castOther.getIdimg()!=null && this.getIdimg().equals(castOther.getIdimg()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getIdnews() == null ? 0 : this.getIdnews().hashCode() );
         result = 37 * result + ( getIdimg() == null ? 0 : this.getIdimg().hashCode() );
         return result;
   }   





}