package mapping;

import java.util.Set;


/**
 * Tipofile generated by hbm2java
 */

public class Tipofile  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String tipo;
     private String estensione;
     private String icona;
     private Set downloads;


    // Constructors

    /** default constructor */
    public Tipofile() {
    }
    
    /** constructor with id */
    public Tipofile(Integer id) {
        this.id = id;
    }

    

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }

    public String getEstensione() {
        return this.estensione;
    }
    
    public void setEstensione(String estensione) {
        this.estensione = estensione;
    }

    public String getIcona() {
        return this.icona;
    }
    
    public void setIcona(String icona) {
        this.icona = icona;
    }

    public Set getDownloads() {
        return this.downloads;
    }
    
    public void setDownloads(Set downloads) {
        this.downloads = downloads;
    }
   








}