package mapping;


/**
 * Azionista generated by hbm2java
 */

public class Azionista  implements java.io.Serializable {


    // Fields    

     private AzionistaId id;


    // Constructors

    /** default constructor */
    public Azionista() {
    }
    
    /** constructor with id */
    public Azionista(AzionistaId id) {
        this.id = id;
    }

    

   
    // Property accessors

    public AzionistaId getId() {
        return this.id;
    }
    
    public void setId(AzionistaId id) {
        this.id = id;
    }
   








}