package mapping;

import java.util.Date;


/**
 * BambinoannoviewId generated by hbm2java
 */

public class BambinoannoviewId  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private String nome;
     private String sesso;
     private String indirizzo;
     private String citta;
     private String nazione;
     private Date datanascita;
     private String scuola;
     private String descrizione;
     private Integer anno;
     private Integer costo;


    // Constructors

    public Integer getCosto() {
		return costo;
	}





	public void setCosto(Integer costo) {
		this.costo = costo;
	}





	/** default constructor */
    public BambinoannoviewId() {
    }
    

    

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    public String getSesso() {
        return this.sesso;
    }
    
    public void setSesso(String sesso) {
        this.sesso = sesso;
    }

    public String getIndirizzo() {
        return this.indirizzo;
    }
    
    public void setIndirizzo(String indirizzo) {
        this.indirizzo = indirizzo;
    }

    public String getCitta() {
        return this.citta;
    }
    
    public void setCitta(String citta) {
        this.citta = citta;
    }

    public String getNazione() {
        return this.nazione;
    }
    
    public void setNazione(String nazione) {
        this.nazione = nazione;
    }

    public Date getDatanascita() {
        return this.datanascita;
    }
    
    public void setDatanascita(Date datanascita) {
        this.datanascita = datanascita;
    }

    public String getScuola() {
        return this.scuola;
    }
    
    public void setScuola(String scuola) {
        this.scuola = scuola;
    }

    public String getDescrizione() {
        return this.descrizione;
    }
    
    public void setDescrizione(String descrizione) {
        this.descrizione = descrizione;
    }

    public Integer getAnno() {
        return this.anno;
    }
    
    public void setAnno(Integer anno) {
        this.anno = anno;
    }
   



   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof BambinoannoviewId) ) return false;
		 BambinoannoviewId castOther = ( BambinoannoviewId ) other; 
         
		 return ( (this.getId()==castOther.getId()) || ( this.getId()!=null && castOther.getId()!=null && this.getId().equals(castOther.getId()) ) )
 && ( (this.getNome()==castOther.getNome()) || ( this.getNome()!=null && castOther.getNome()!=null && this.getNome().equals(castOther.getNome()) ) )
 && ( (this.getSesso()==castOther.getSesso()) || ( this.getSesso()!=null && castOther.getSesso()!=null && this.getSesso().equals(castOther.getSesso()) ) )
 && ( (this.getIndirizzo()==castOther.getIndirizzo()) || ( this.getIndirizzo()!=null && castOther.getIndirizzo()!=null && this.getIndirizzo().equals(castOther.getIndirizzo()) ) )
 && ( (this.getCitta()==castOther.getCitta()) || ( this.getCitta()!=null && castOther.getCitta()!=null && this.getCitta().equals(castOther.getCitta()) ) )
 && ( (this.getNazione()==castOther.getNazione()) || ( this.getNazione()!=null && castOther.getNazione()!=null && this.getNazione().equals(castOther.getNazione()) ) )
 && ( (this.getDatanascita()==castOther.getDatanascita()) || ( this.getDatanascita()!=null && castOther.getDatanascita()!=null && this.getDatanascita().equals(castOther.getDatanascita()) ) )
 && ( (this.getScuola()==castOther.getScuola()) || ( this.getScuola()!=null && castOther.getScuola()!=null && this.getScuola().equals(castOther.getScuola()) ) )
 && ( (this.getDescrizione()==castOther.getDescrizione()) || ( this.getDescrizione()!=null && castOther.getDescrizione()!=null && this.getDescrizione().equals(castOther.getDescrizione()) ) )
 && ( (this.getAnno()==castOther.getAnno()) || ( this.getAnno()!=null && castOther.getAnno()!=null && this.getAnno().equals(castOther.getAnno()) ) );
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + ( getId() == null ? 0 : this.getId().hashCode() );
         result = 37 * result + ( getNome() == null ? 0 : this.getNome().hashCode() );
         result = 37 * result + ( getSesso() == null ? 0 : this.getSesso().hashCode() );
         result = 37 * result + ( getIndirizzo() == null ? 0 : this.getIndirizzo().hashCode() );
         result = 37 * result + ( getCitta() == null ? 0 : this.getCitta().hashCode() );
         result = 37 * result + ( getNazione() == null ? 0 : this.getNazione().hashCode() );
         result = 37 * result + ( getDatanascita() == null ? 0 : this.getDatanascita().hashCode() );
         result = 37 * result + ( getScuola() == null ? 0 : this.getScuola().hashCode() );
         result = 37 * result + ( getDescrizione() == null ? 0 : this.getDescrizione().hashCode() );
         result = 37 * result + ( getAnno() == null ? 0 : this.getAnno().hashCode() );
         return result;
   }   





}