package mapping;

import mapping.Anagrafe;



/**
 * Famiglia generated by hbm2java
 */

public class Famiglia  implements java.io.Serializable {


    // Fields    

     private FamigliaId id;
     private Anagrafe anagrafeById1;
     private Anagrafe anagrafeById2;


    // Constructors

    /** default constructor */
    public Famiglia() {
    }
    
    /** constructor with id */
    public Famiglia(FamigliaId id) {
        this.id = id;
    }

    

   
    // Property accessors

    public FamigliaId getId() {
        return this.id;
    }
    
    public void setId(FamigliaId id) {
        this.id = id;
    }

    public Anagrafe getAnagrafeById1() {
        return this.anagrafeById1;
    }
    
    public void setAnagrafeById1(Anagrafe anagrafeById1) {
        this.anagrafeById1 = anagrafeById1;
    }

    public Anagrafe getAnagrafeById2() {
        return this.anagrafeById2;
    }
    
    public void setAnagrafeById2(Anagrafe anagrafeById2) {
        this.anagrafeById2 = anagrafeById2;
    }
   








}