package mapping;

import java.util.Set;


/**
 * Gruppo generated by hbm2java
 */

public class Gruppo  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Integer tipo;
     private String nome;
     private Set contos;


    // Constructors

    /** default constructor */
    public Gruppo() {
    }
    
    /** constructor with id */
    public Gruppo(Integer id) {
        this.id = id;
    }

    

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Integer getTipo() {
        return this.tipo;
    }
    
    public void setTipo(Integer tipo) {
        this.tipo = tipo;
    }

    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    public Set getContos() {
        return this.contos;
    }
    
    public void setContos(Set contos) {
        this.contos = contos;
    }
   








}