package mapping;

import java.util.Set;


/**
 * Socio generated by hbm2java
 */

public class Socio  implements java.io.Serializable {


    // Fields    

     private Integer tessera;
     private Anagrafe anagrafe;
     private String note;
     private Set pagamentosocis;


    // Constructors

    /** default constructor */
    public Socio() {
    }
    
    /** constructor with id */
    public Socio(Integer tessera) {
        this.tessera = tessera;
    }

    

   
    // Property accessors

    public Integer getTessera() {
        return this.tessera;
    }
    
    public void setTessera(Integer tessera) {
        this.tessera = tessera;
    }

    public Anagrafe getAnagrafe() {
        return this.anagrafe;
    }
    
    public void setAnagrafe(Anagrafe anagrafe) {
        this.anagrafe = anagrafe;
    }

    public String getNote() {
        return this.note;
    }
    
    public void setNote(String note) {
        this.note = note;
    }

    public Set getPagamentosocis() {
        return this.pagamentosocis;
    }
    
    public void setPagamentosocis(Set pagamentosocis) {
        this.pagamentosocis = pagamentosocis;
    }
   








}