package mapping;

import java.util.Set;


/**
 * Progetti generated by hbm2java
 */

public class Progetti  implements java.io.Serializable {


    // Fields    

     private Integer id;
     private Regioni regioni;
     private Immagini immagini;
     private String titolo;
     private String sottotitolo;
     private String testo;
     private String inizio;
     private String fine;
     private String luogo;
     private String home;
     private Integer realizzato;
     private Set progettiimgs;


    // Constructors

    /** default constructor */
    public Progetti() {
    }
    
    /** constructor with id */
    public Progetti(Integer id) {
        this.id = id;
    }

    

   
    // Property accessors

    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

    public Regioni getRegioni() {
        return this.regioni;
    }
    
    public void setRegioni(Regioni regioni) {
        this.regioni = regioni;
    }

    public Immagini getImmagini() {
        return this.immagini;
    }
    
    public void setImmagini(Immagini immagini) {
        this.immagini = immagini;
    }

    public String getTitolo() {
        return this.titolo;
    }
    
    public void setTitolo(String titolo) {
        this.titolo = titolo;
    }

    public String getSottotitolo() {
        return this.sottotitolo;
    }
    
    public void setSottotitolo(String sottotitolo) {
        this.sottotitolo = sottotitolo;
    }

    public String getTesto() {
        return this.testo;
    }
    
    public void setTesto(String testo) {
        this.testo = testo;
    }

    public String getInizio() {
        return this.inizio;
    }
    
    public void setInizio(String inizio) {
        this.inizio = inizio;
    }

    public String getFine() {
        return this.fine;
    }
    
    public void setFine(String fine) {
        this.fine = fine;
    }

    public String getLuogo() {
        return this.luogo;
    }
    
    public void setLuogo(String luogo) {
        this.luogo = luogo;
    }

    public String getHome() {
        return this.home;
    }
    
    public void setHome(String home) {
        this.home = home;
    }

    public Integer getRealizzato() {
        return this.realizzato;
    }
    
    public void setRealizzato(Integer realizzato) {
        this.realizzato = realizzato;
    }

    public Set getProgettiimgs() {
        return this.progettiimgs;
    }
    
    public void setProgettiimgs(Set progettiimgs) {
        this.progettiimgs = progettiimgs;
    }
   








}